version: "3.8"
services:
  db:
    image: mariadb
    container_name: db
    restart: always
    networks:
      - local
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-h"
        - localhost
      timeout: 20s
      retries: 10
    volumes:
      - "db-data:/var/lib/mysql"
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - local
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: "${DB_USERNAME}"
      PMA_PASSWORD: "${DB_PASSWORD}"
      UPLOAD_LIMIT: 10M
  web:
    build: .
    container_name: web
    depends_on:
      db:
        condition: service_healthy
    networks:
      - local
    ports:
      - "8000:80"
    volumes:
      - ".:/var/www/html:delegated"
      - "web-storage:/var/www/html/storage"
networks:
  local: null
volumes:
  db-data: null
  web-storage: null
