version: "3.8"
services:
  mariadb:
    image: mariadb
    container_name: mariadb
    restart: always
    networks:
      - default
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
    healthcheck:
      test:
        - CMD
        - mysqladmin
        - ping
        - "-h"
        - localhost
      timeout: 20s
      retries: 10
    volumes:
      - db
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    depends_on:
      mariadb:
        condition: service_healthy
    restart: always
    networks:
      - default
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: "${DB_PASSWORD}"
      UPLOAD_LIMIT: 10M
  web:
    build: .
    container_name: web
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - default
    ports:
      - "8000:80"
    volumes:
      - ".:/var/www/html:delegated"
networks:
  default: null
volumes:
  db:
    driver: local
